# Generated by Django 3.2.13 on 2022-06-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'icons',
            },
        ),
    ]
